version: '3'
services:
  production: &prod
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      - DEBUG
      - BUILD_PREFIX
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-common
    network_mode: host
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
volumes:
  exa-volume:
