version: "3.5"
services:
  production: &prod
    build:
      context: .
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      - DEBUG
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - BUILD_PREFIX
  dev: &dev
    <<: *prod
    image: keboola/php-storage-driver-common
    network_mode: host
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build: etc/docker/xdebug
  controllerWorker:
    <<: *dev
    command:
      - /usr/local/bin/rr
      - serve
      - -c
      - /code/Controller/.rr.yaml
volumes:
  exa-volume:
